### ISSUE TITLE
Add support to redirect

### ISSUE THREAD

**Issue by thenets** [thenets/ansible-nginx#1]
Create two types of Nginx behavior:
- Proxy (already exist)
- Redirect, a simple 302 signal.

**Comment by thenets** [comment]
It's not necessary anymore. The feature #8 already allow the redirect using a single line.

Example:
```yaml
[...]
      # Simple permanent redirect
      - domain: "temp.example.com"
        location_extra: |
          rewrite ^ https://www.example.com? permanent;
```

For more information about temporary and permanent redirect check this link:
https://www.digitalocean.com/community/tutorials/how-to-create-temporary-and-permanent-redirects-with-nginx
